import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  h1: {
    fontFamily: 'Inter-Bold',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 22,
    lineHeight: 32,
    letterSpacing: 0.5,
    color: '#C4C4C4',
  },
  h2: {
    fontFamily: 'Inter-Bold',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 17,
    lineHeight: 27,
    letterSpacing: 0.5,
    color: '#C4C4C4',
  },
  h3: {
    fontFamily: 'Inter-Bold',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 15,
    lineHeight: 25,
    letterSpacing: 0.5,
    color: '#C4C4C4',
  },
  p1: {
    fontFamily: 'Inter-Medium',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 17,
    lineHeight: 27,
    letterSpacing: 0.5,
    color: '#C4C4C4',
  },
  p2: {
    fontFamily: 'Inter-Medium',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 15,
    lineHeight: 25,
    letterSpacing: 0.5,
    color: '#C4C4C4',
  },
  s: {
    fontFamily: 'Inter-Medium',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 12,
    lineHeight: 15,
    letterSpacing: 0.5,
    color: '#C4C4C4',
  },
  bt1: {
    fontFamily: 'Inter-Bold',
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 18,
    letterSpacing: 0.2,
    textAlign: 'center',
  },
  bt2: {
    fontFamily: 'Inter-Bold',
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 15,
    letterSpacing: 0.2,
    textAlign: 'center',
  },
});

export default styles;
