export default [
  {
    id: 1,
    text: 'Step-1:-  5 ounces mixed spring greens',
    img: require('../../assets/images/green.png'),
    rating: '5.0',
    icon: require('../../assets/icons/star-icon.svg'),
  },
  {
    id: 2,
    text: 'Step-2:-  1 ripe avocado',
    img: require('../../assets/images/avocado.png'),
    rating: '4.1',
    icon: require('../../assets/icons/star-icon.svg'),
  },
  {
    id: 3,
    text: 'Step-3:-  half a small red onion',
    img: require('../../assets/images/onions.png'),
    rating: '3.8',
    icon: require('../../assets/icons/star-icon.svg'),
  },
  {
    id: 4,
    text: 'Step-4:-  1 cup halved cherry tomatoes',
    img: require('../../assets/images/tomatoes.png'),
    rating: '4.6',
    icon: require('../../assets/icons/star-icon.svg'),
  },
  {
    id: 5,
    text: 'Step-5:-  2/3 cup roughly-chopped fresh cilantro.',
    img: require('../../assets/images/chopped.png'),
    rating: '4.3',
    icon: require('../../assets/icons/star-icon.svg'),
  },
  {
    id: 6,
    text: 'Step-6:-  1/3 cup pepitas',
    img: require('../../assets/images/papita.png'),
    rating: '4.0',
    icon: require('../../assets/icons/star-icon.svg'),
  },
  {
    id: 7,
    text: 'Step-7:-  1/2 cup crumbled queso fresco or cotija cheese.',
    img: require('../../assets/images/cheese.png'),
    rating: '4.1',
    icon: require('../../assets/icons/star-icon.svg'),
  },
];
