export default [
  {
    id: 1,
    img: require('../../assets/pics/EroticSandwich.png'),
    time: '25`',
    rating: '4.0',
    TextHeading: 'Erotic Sandwich',
    Description: 'Amazing Combo of different taste',
  },
  {
    id: 2,
    img: require('../../assets/pics/pulavspecial.png'),
    time: '30`',
    rating: '4.5',
    TextHeading: 'Special Pulav',
    Description: 'Amazing Combo food includes Kadhi and Sambhara',
  },
  {
    id: 3,
    img: require('../../assets/pics/WinterSpecialVasana.png'),
    time: '15`',
    rating: '4.0',
    TextHeading: 'Special Winter Vasana',
    Description: 'An Amazing Winter Sweet',
  },
  {
    id: 4,
    img: require('../../assets/pics/lipsmackingsoup.png'),
    time: '35`',
    rating: '5.0',
    TextHeading: 'Lip Smacking Soup',
    Description: 'Amazing Combo of sweet and souvery',
  },
  {
    id: 5,
    img: require('../../assets/pics/breadwich.png'),
    time: '30`',
    rating: '5.0',
    TextHeading: 'Breadwich',
    Description: 'Amazing breadwich with Sauces and Salad',
  },
];
